title: "Tristan Allen"
description: "Portfolio"
url: "https://tristanta.github.io"
baseurl: "/tristan-allen-portfolio"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dark" # options: default, air, dark, etc.

markdown: kramdown
permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      toc: false

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/TristanTA"